helpdesk/Controllers/OrderCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using helpdesk.Models;

namespace helpdesk.Controllers
{
    public class OrderCommentsController : Controller
    {
        private helpdeskContext db = new helpdeskContext();

        // GET: OrderComments
        public ActionResult Index()
        {
            return View(db.OrderComment.ToList());
        }

        // GET: OrderComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderComment orderComment = db.OrderComment.Find(id);
            if (orderComment == null)
            {
                return HttpNotFound();
            }
            return View(orderComment);
        }

        // GET: OrderComments/Create
        public ActionResult Create(int? orderId)
        {
            if (orderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "StatusName");

            OrderComment orderComment = new OrderComment();
            orderComment.OrderId = (int)orderId;
            
            if (orderComment == null)
            {
                return HttpNotFound();
            }
            return View(orderComment);
        }

        // POST: OrderComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderCommentId,Text,OrderId")] OrderComment orderComment, int StatusId)
        {
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "StatusName");
            if (ModelState.IsValid)
            {
                Status status = db.Status.Find(StatusId);
                Order order = db.Orders.Find(orderComment.OrderId);
                order.Status = status;
                
                if (status == db.Status.Single(s => s.StatusName == "zamknięte"))
                {
                    order.TimeClosed = DateTime.Now;
                }
                else
                {
                    order.TimeClosed = null;
                }

                orderComment.Username = getUserName();
                orderComment.Time = DateTime.Now;
                orderComment.Status = status;
                orderComment.Order = order;
                db.OrderComment.Add(orderComment);
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Orders", new { Id = orderComment.OrderId });
            }
            return View(orderComment);
        }

        string getUserName()
        {
            return User.Identity.Name.ToLower();
        }

        // GET: OrderComments/AddComment
        public ActionResult AddComment(int? orderId)
        {
            if (orderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderComment orderComment = new OrderComment();
            orderComment.OrderId = (int)orderId;

            if (orderComment == null)
            {
                return HttpNotFound();
            }
            return View(orderComment);
        }

        // POST: OrderComments/AddComment
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment([Bind(Include = "OrderCommentId,Text,OrderId")] OrderComment orderComment)
        {
            if (ModelState.IsValid)
            {                
                Order order = db.Orders.Find(orderComment.OrderId);
                orderComment.Time = DateTime.Now;
                orderComment.Status = order.Status;
                orderComment.Order = order;
                orderComment.Username = getUserName();
                db.OrderComment.Add(orderComment);
              //  db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Orders", new { Id = orderComment.OrderId });
            }
            return View(orderComment);
        }


        // GET: OrderComments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderComment orderComment = db.OrderComment.Find(id);
            if (orderComment == null)
            {
                return HttpNotFound();
            }
            return View(orderComment);
        }

        // POST: OrderComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderCommentId,Time,Text")] OrderComment orderComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderComment);
        }

        // GET: OrderComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderComment orderComment = db.OrderComment.Find(id);
            if (orderComment == null)
            {
                return HttpNotFound();
            }
            return View(orderComment);
        }

        // POST: OrderComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderComment orderComment = db.OrderComment.Find(id);
            db.OrderComment.Remove(orderComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

helpdesk/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using helpdesk.Models;
using helpdesk.ViewModels;
using PagedList;

namespace helpdesk.Controllers
{
    public class OrdersController : Controller
    {
        private helpdeskContext db = new helpdeskContext();

        // GET: Orders
        public ActionResult Index(int? page, int? StatusId, int? CategoryId, string Query)
        {
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "StatusName");
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");

            string username = getUserName();
            visitCount();
            bool isAdmin = checkCredentials(username);
            ViewBag.isAdmin = isAdmin;

            IQueryable<Order> orders =null;
            if (isAdmin)
            {
                orders = db.Orders.Include(o => o.Category);
            }
            else
            {
                orders = db.Orders.Where(o => o.UserName == username).Include(o => o.Category);
            }

            if (!String.IsNullOrEmpty(Query))
            {
                orders = orders.Where(s => s.Content.Contains(Query));
            }

            if (StatusId > 0)
            {
                orders = orders.Where(p => p.Status.StatusId == StatusId);
            }

            if (CategoryId > 0)
            {
                orders = orders.Where(p => p.Category.CategoryId==CategoryId);
            }


            int pageSize = 10;
            int pageNumber = (page ?? 1);

            
             IPagedList<Order> ordersPaged = orders.OrderBy(o => o.Status.StatusId).ThenBy(o => o.TimeCreated).ToPagedList(pageNumber, pageSize);

            return View(ordersPaged);
        }

        // GET: Orders
        public ActionResult ReportIndex()
        {
            DateTime start = DateTime.Parse("2017-01-01");
            DateTime end = DateTime.Now;

            Report report = new Report(start,end);
            ViewBag.Summary = report.OrderSummary();
            ViewBag.OrdersByStatus = report.OrdersByStatus();
            ViewBag.OrdersByCategory = report.OrdersByCategory();
            return View();
        }

        string getUserName()
        {
            return User.Identity.Name.ToLower();
        }

        bool checkCredentials(string username)
        {
            bool isAdmin = false;
            try
            {
                AppUser user = db.AppUser.Include(p => p.Credential).Single(p => p.Username == username);
                if (user.Credential.CredentialId == 1)
                {
                    isAdmin = true;
                }
            }
            catch (Exception)
            {
                isAdmin = false;
            }
            return isAdmin;
        }

        void visitCount()
        {
            string username = getUserName();
            if (db.AppUser.Any(p => p.Username == username))
            {
                AppUser appUser = db.AppUser.Single(p => p.Username == username);
                appUser.Visits++;
                db.Entry(appUser).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                Credential credential = db.Credentials.Single(p => p.CredentialId==2);
                AppUser appUser = new AppUser { Username = username, Visits = 1, Credential= credential };
                db.AppUser.Add(appUser);
                db.SaveChanges();
            }
        }
        
        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string username = getUserName();
            ViewBag.isAdmin = checkCredentials(username);

            OrderDetailsViewModel orderDetailsViewModel = new OrderDetailsViewModel();
            orderDetailsViewModel.Order = db.Orders.Find(id);
            orderDetailsViewModel.OrderComments = db.OrderComment.Where(p => p.Order.OrderId == id).Include(p=>p.Status);

            if (orderDetailsViewModel == null)
            {
                return HttpNotFound();
            }
            return View(orderDetailsViewModel);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,Urgent,Content")] Order order, int CategoryId)
        {
            if (ModelState.IsValid)
            {
                order.Category = db.Categories.Single(p => p.CategoryId == CategoryId);
                order.Status = db.Status.Single(p => p.StatusName == "nowe");
                order.TimeCreated = DateTime.Now;
                order.UserName = getUserName();
                db.Orders.Add(order);

                OrderComment orderComment = new OrderComment();
                orderComment.Order = order;
                orderComment.Status = order.Status;
                orderComment.Time = order.TimeCreated;
                orderComment.Text = "Utworzono zgłoszenie";
                db.OrderComment.Add(orderComment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Category = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", order.Category);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserName,CategoryId,TimeCreated,TimeClosed,Urgent,Content")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", order.Category);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Orders/Cancel/5
        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public ActionResult Cancel(int id, string comment)
        {
            Order order = db.Orders.Find(id);
            order.Status = db.Status.Single(p => p.StatusName == "anulowane");
            order.TimeClosed = DateTime.Now;

            OrderComment orderComment = new OrderComment();
            orderComment.Order = order;
            orderComment.Status = order.Status;
            orderComment.Time = order.TimeCreated;
            orderComment.Text = comment;

            db.OrderComment.Add(orderComment);
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

helpdesk/Views/Orders/Cancel.cshtml
@model helpdesk.Models.Order

@{
    ViewBag.Title = "Delete";
}
<h3>Anulować zgłoszenie?</h3>
<div>
    <hr />
    @*<dl class="dl-horizontal">
        <dt>
            Zgłoszenie nr @Html.DisplayFor(model => model.OrderId)
        </dt>
    </dl>*@

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Potwierdź anulowanie" class="btn btn-outline-danger" />
        @Html.ActionLink("Powrót", "Details", "Orders", new { id = Model.OrderId }, new { @class = "btn btn-outline-primary" })
    </div>
    }
</div>

helpdesk/Views/Orders/Create.cshtml
@model helpdesk.Models.Order

@{
    ViewBag.Title = "Nowe zgłoszenie";
}

<h2>Nowe zgłoszenie</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Urgent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Urgent)
                @Html.ValidationMessageFor(model => model.Urgent, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, htmlAttributes: new { @class = "form-control", @rows = "5" })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Powrót", "Index", null, htmlAttributes: new { @class = "btn btn-outline-primary" })
            <input type="submit" value="Utwórz" class="btn btn-outline-success" />
        </div>
    </div>
</div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

helpdesk/Views/Orders/Delete.cshtml
@model helpdesk.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeClosed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeClosed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Urgent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Urgent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

helpdesk/Views/Orders/Details.cshtml
@model helpdesk.ViewModels.OrderDetailsViewModel

@{
    int orderId = Model.Order.OrderId;
}

@{
    ViewBag.Title = "Zgłoszenie nr " + orderId;
}


<h2>Zgłoszenie nr @orderId</h2>

<table class="table table-responsive">
    <thead class="thead-default">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order.Category.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.Urgent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.TimeCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.TimeClosed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.ServiceTime)
            </th>
        </tr>
    </thead>
    @{
        string rowTheme = "table-light";
        if (Model.Order.Urgent)
        {
            rowTheme = "table-danger";
        }
    }
    <tr class="@rowTheme">
        <td>
            @Html.DisplayFor(model => model.Order.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.Status.StatusName)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.Urgent)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.UserName)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.TimeCreated)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.TimeClosed)
        </td>
        <td>
            @Html.DisplayFor(model => model.Order.ServiceTime)
        </td>
        </trclass="@rowTheme">
</table>
<dt>
    @Html.DisplayNameFor(model => model.Order.Content)
</dt>
<div class="card">
    <div class="card-body">
        @Html.DisplayFor(model => model.Order.Content)
    </div>
</div>

<p></p>

<table class="table table-sm table-responsive-sm table-striped">
    <thead class="thead-default">
        <tr>
            <th>
                #
            </th>
            <th>
                Czas
            </th>
            <th>
                Status
            </th>
            <th>
                Użytkownik
            </th>
            <th>
                Treść
            </th>
        </tr>
    </thead>
    @{
        int i = 1;
        foreach (var item in Model.OrderComments)
        {
    <tr>
        <td>
            @i
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.StatusName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        <td>
    </tr>
            i++;
        }
    }
</table>

@Html.ActionLink("Powrót", "Index", null, htmlAttributes: new { @class = "btn btn-outline-primary" })
@{
        if (Model.Order.Status.StatusName != "zamknięte" && Model.Order.Status.StatusName != "anulowane")
        {
        @Html.ActionLink("Anuluj zgłoszenie", "Cancel", "Orders", new { id = @orderId }, htmlAttributes: new { @class = "btn btn-outline-danger" })
        @Html.ActionLink("Dodaj komentarz", "AddComment", "OrderComments", new { orderId = @orderId }, htmlAttributes: new { @class = "btn btn-outline-success ml-1" })
        }
        else
        {
        @Html.ActionLink("Anuluj zgłoszenie", "Cancel", "Orders", new { id = @orderId }, htmlAttributes: new { @class = "btn btn-light disabled" })
        @Html.ActionLink("Dodaj komentarz", "AddComment", "OrderComments", new { orderId = @orderId }, htmlAttributes: new { @class = "btn btn-light disabled ml-1" })
        }
        if (ViewBag.isAdmin)
        {
        @Html.ActionLink("Zmień status", "Create", "OrderComments", new { orderId = @orderId }, htmlAttributes: new { @class = "btn btn-outline-warning ml-1" })
        }
}

helpdesk/Views/Orders/Edit.cshtml
@model helpdesk.Models.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeClosed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeClosed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeClosed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Urgent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Urgent)
                    @Html.ValidationMessageFor(model => model.Urgent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

helpdesk/Views/Orders/ReportIndex.cshtml
@model helpdesk.Models.Order

@{
    ViewBag.Title = "Raporty";
}

@{ var items = this.ViewBag.Summary as Dictionary<string, string>; }

<table class="table table-responsive">

    @foreach (var item in items)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Key)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
        </tr>
    }

</table>

@*@{ var itemsByStatus = this.ViewBag.OrdersByStatus as Dictionary<string, string>; }

<table class="table table-responsive">

    @foreach (var itemByStatus in itemsByStatus)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => itemByStatus.Key)
            </td>
            <td>
                @Html.DisplayFor(modelItem => itemByStatus.Value)
            </td>
        </tr>
    }

</table>*@